config/routes.rb
Rails.application.routes.draw do
  resources :onepages
  root 'onepages#show'

  resources :bets
  resources :teams
  resources :games
  resource :user
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: %i[ show edit update destroy ]

  # GET /bets or /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1 or /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets or /bets.json
  def create
    @bet = Bet.new(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to bet_url(@bet), notice: "Bet was successfully created." }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1 or /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to bet_url(@bet), notice: "Bet was successfully updated." }
        format.json { render :show, status: :ok, location: @bet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1 or /bets/1.json
  def destroy
    @bet.destroy

    respond_to do |format|
      format.html { redirect_to bets_url, notice: "Bet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bet_params
      params.require(:bet).permit(:game_id, :bet)
    end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_bet.html.erb
<div id="<%= dom_id bet %>">
  <p>
    <strong>Game:</strong>
    <%= bet.game_id %>
  </p>

  <p>
    <strong>Bet:</strong>
    <%= bet.bet %>
  </p>

</div>

app/views/bets/_form.html.erb
<%= form_with(model: bet) do |form| %>
  <% if bet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
        <% bet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :game_id, style: "display: block" %>
    <%= form.number_field :game_id %>
  </div>

  <div>
    <%= form.label :bet, style: "display: block" %>
    <%= form.text_field :bet %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render "form", bet: @bet %>

<br>

<div>
  <%= link_to "Show this bet", @bet %> |
  <%= link_to "Back to bets", bets_path %>
</div>

app/views/bets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bets</h1>

<div id="bets">
  <% @bets.each do |bet| %>
    <%= render bet %>
    <p>
      <%= link_to "Show this bet", bet %>
    </p>
  <% end %>
</div>

<%= link_to "New bet", new_bet_path %>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render "form", bet: @bet %>

<br>

<div>
  <%= link_to "Back to bets", bets_path %>
</div>

app/views/bets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bet %>

<div>
  <%= link_to "Edit this bet", edit_bet_path(@bet) %> |
  <%= link_to "Back to bets", bets_path %>

  <%= button_to "Destroy this bet", @bet, method: :delete %>
</div>